### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by anovik** [anovik/SmartCommander#56]
Options to search plain text and regex in file name and file content. 
Show the list of files with possibility to nagivate to each of them.

**Comment by Diaskhan** [comment]
https://github.com/files-community/Files

**Comment by Diaskhan** [comment]
@anovik  maybe we shoul use 
https://docs.avaloniaui.net/docs/reference/controls/treedatagrid/
as result component ?

![image](https://github.com/user-attachments/assets/8e3d7392-0861-428f-b1a6-6d9ef6c57b6d)

because it goest fore fluent when we searching example
![image](https://github.com/user-attachments/assets/731a022b-d9e0-49d9-8ab2-3a9615ff7e48)
